package model

// Event represents a structured event
type Event struct {
	Type           string `json:"type"`
	ConversationID string `json:"conversation_id,omitempty"`
	MessageID      string `json:"msg_id,omitempty"`
	Backend        string `json:"backend,omitempty"`
	Data           any    `json:"data"`
}

// Host event type constants - generated by cs-cloud host process
const (
	// File system events
	EventTypeHostFileCreated = "host.file.created"
	EventTypeHostFileUpdated = "host.file.updated"
	EventTypeHostFileDeleted = "host.file.deleted"
	EventTypeHostFileRenamed = "host.file.renamed"

	// Git events
	EventTypeHostGitBranchChanged = "host.git.branch.changed"
	EventTypeHostGitCommit        = "host.git.commit"
	EventTypeHostGitStatusChanged = "host.git.status.changed"
	EventTypeHostGitRemoteChanged = "host.git.remote.changed"
)
